version: '3.6'

services:
  razorpageslearn:
    image: ${DOCKER_REGISTRY-}razorpageslearn
    build:
      context: .
      dockerfile: RazorPagesLearn/Dockerfile
    ports:
      - '9299:9299'
    environment:
      - HTTP_PORT=9299
      