version: '3.6'

services:
  razorpageslearn:
    image: ${DOCKER_REGISTRY-}razorpageslearn
    build:
      context: .
      dockerfile: RazorPagesLearn/Dockerfile
    ports:
      - '9299:9299'
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
